services: 

  app: 
    build: .
  postgres-db:
    image: postgres:16
    container_name: caisse_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
