services: 
  caisse-1: 
    build: .
    depends-on: postgres-db
  caisse-2: 
    build: .
    depends-on: postgres-db
  caisse-3: 
    build: .
    depends-on: postgres-db
  postgres-db:
    image: postgres:16
    container_name: caisse_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
