services: 
  caisse-1: 
      build: .
      depends_on: 
      - db
  caisse-2: 
      build: .
      depends_on: 
      - db
  caisse-3: 
      build: .
      depends_on: 
      - db
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
